spring:
  mail:
    host: smtp.qq.com
    username: qq邮箱
    password: 授权码
    properties: 
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
      mail.smtp.timeout: 10000
    to: 接收方邮箱
      
